spring:
    application:
        name: course-catalog-service
message: Hello from default profile

# ---
# spring.config.active.on-profile: prod
# message: Hello from prod profile
# ---
# spring.config.active.on-profile: non-prod
# message: Hello from non-prod profile